# Generated by Django 2.0.1 on 2018-01-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_name',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
